#result to tun app
apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: result-app
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80

#All comand to run all service
########################################
#1)kubectl get svc
#2)kubectl create -f voting-app-pod.yaml
#3)kubectl create -f voting-app-service.yaml
#4)kubectl get pods,svc
#5)minikube service voting-service --url
#6)kubectl create -f redis-pod.yaml
#7)kubectl create -f redis-service.yaml
#8)kubectl get pods,svc
#9)kubectl create -f postgres-pod.yaml
#10)kubectl create -f postgres-service.yaml
#11)kubectl get pods,svc
#12)kubectl create -f voting-app-pod.yaml
#13)kubectl create -f worker-app-pod.yaml
#14)kubectl get pods,svc
#15)kubectl create -f result-app-service.yaml
#16)minikube service result-service --url
#########################################